# default

server:
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false
  port: 12816

application:
  version: ${ext.appVersion}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foodage_test
    username: root
    password: ENC(xkFnya3z7VNC6ZB6uP40727FrkbtsOfbq43XPqNdrTL85ODRthMD+NrSNBG808wcksJSZsVFm+jJBLOisQCblg==)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # 개발 환경에서만 사용

logging:
  level:
    com.fourdays.foodage: DEBUG
