# ec2 배포

server:
  port: 12816

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foodage_database
    username: root
    password: ENC(P9e4T6LWe/YjgSDOp47HlOyukMcijCpDF+uWD/iGIHbOlx/PANpsNdx5CbFtg9b/)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  header: Authorization
  # HS512 알고리즘을 사용하므로 512bit, 64byte 이상의 secret key를 사용
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 토큰 만료 시간
  access-token-expiration-seconds: 1800 # 30m
  refresh-token-expiration-seconds: 86400 #24h

logging:
  level:
    com.fourdays.foodage: DEBUG

# local 환경, dev 환경 분리
oauth:
  kakao:
    client_id: fb2a4ad47b5f715e785754c4ec10a4c9
    redirect_uri: http://3.36.239.143/api/oauth/kakao/login
    client-secret: jz2ITUF1AzDGJnPNT6S9YT4pADSlL5Nr
    scope: account_email

  naver:
    client_id: ikvTx89ygb3cwlWkF39g
    redirect_uri: http://3.36.239.143/api/oauth/naver/login
    client_secret: D93Z6PoGko
    scope:

  google:
    client_id:
    redirect_uri: http://3.36.239.143/api/oauth/google/login
    client_secret:
    scope:

application:
  domain: 3.36.239.143
  client:
    base-url: http://3.36.239.143
