# local

server:
  port: 12816

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foodage_test
    username: root
    password: ENC(P9e4T6LWe/YjgSDOp47HlOyukMcijCpDF+uWD/iGIHbOlx/PANpsNdx5CbFtg9b/)
  jpa:
    show-sql: true
  #    hibernate:
  #      ddl-auto: create # 개발 환경에서만 사용
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 64byte 이상의 secret key를 사용해야 한다.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 토큰 만료 시간
  access-token-expiration-seconds: 3600 # 1h
  refresh-token-expiration-seconds: 86400 #24h

logging:
  level:
    com.fourdays.foodage: DEBUG

# local 환경, dev 환경 분리
oauth:
  kakao:
    client_id: 82f26cfc6fc100e96d6412872692f5b0
    redirect_uri: http://localhost:12816/api/oauth/kakao/login
    client-secret: 1aKOP7wMRrENEpVAZcdFyP0Xat6JwSO0
    scope: account_email

  naver:
    client_id: j6ztPQjigmcPexSsU4Dz
    redirect_uri: http://localhost:12816/api/oauth/naver/login
    client_secret: EdsUYwGe66
    scope:

application:
  client:
    base-url: http://localhost:3000
