# default

server:
  port: 12816
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

application:
  version: '1.0.5'

spring:
  profiles:
    default: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
