@startuml
header last updated: 2023.11.06.
footer Page %page% of %lastpage%
title
    <size:18> 로그인 프로세스 </size>
end title

'''''''
'actor User as user
box Foodage Client #OldLace
    participant "Client" as client #NavajoWhite
end box
'''''''
    participant "Auth Server" as a_server #NavajoWhite
'''''''
box Foodage Server #OldLace
    participant "Server" as server #NavajoWhite
    database db
end box
'''''''
autonumber


|||
== 로그인 ==

'로그인
client -> server: 서비스 로그인 요청
server -> a_server: GET /oauth/authorize
  note right: Auth Server\n> 카카오, 네이버, 구글 등의 써드파티
a_server -> client: OAuth 계정으로 로그인 요청
client -> a_server: OAuth 계정 로그인, 약관동의 완료
a_server --> server: 인가 코드(Authorization Code) 응답
''' at 발급
server -> a_server: OAuth Access Token 발급 요청 (w. 인가 코드)
  note right: > 이하 A・T
a_server --> server: OAuth A・T 발급
''' at로 사용자 정보 확인
server -> a_server: OAuth A・T로 사용자 정보 요청
a_server --> server: 사용자 정보 응답
server -> db: 사용자 정보 DB 존재 여부 확인
db -> db: 사용자 정보 확인
db --> server: DB에 존재하지 않는 사용자 정보

'회원가입
group 회원가입*
    server -> client: 회원가입 요청
    client -> client: 추가 회원가입 데이터 입력
    client -> server: 회원가입 완료 요청
    server -> db: 회원 정보 추가
    db -> db: 회원 정보 insert
    server -> client: 회원가입 완료 응답
    client --> client: 회원가입 성공
end

|||

@enduml
